imports:
    - { resource: 'ibexa_seo_toolkit_images.yaml' }

fos_rest:
    serializer:
        serialize_null: true
    body_listener: true
    param_fetcher_listener: true
    view:
        failed_validation: 422
        view_response_listener: true
        empty_content: 204
        formats:
            json : true
    zone:
        - { path: '^/api/seo/.*' }
    format_listener:
        rules:
            - { path: '^/api/seo', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
    exception:
        codes:
            'Codein\IbexaSeoToolkit\Exception\ValidationException': 422
            'Codein\IbexaSeoToolkit\Exception\AnalyzeException': 400

doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:         #..
            IbexaSeoToolkitBundle:
                is_bundle: true
                type: annotation
                dir: 'Entity'
                prefix: 'Codein\IbexaSeoToolkit\Entity'

twig:
    paths:
        '%kernel.project_dir%/vendor/codein/ibexa-seo-toolkit/bundle/templates': CodeinIbexaSeoToolkit
