system:
    admin_group:
        ### content view platformui templates
        field_templates:
            - {template: '@IbexaSeoToolkit/content_type/view.html.twig', priority: 0}
        ### contentType (edit/new) platformui templates
        fielddefinition_edit_templates:
            - {template: '@IbexaSeoToolkit/content_type/edit.html.twig', priority: 0}
        admin_ui_forms:
            content_edit_form_templates:
                - { template: '@IbexaSeoToolkit/content/selection.html.twig', priority: -1 }
    site_group:
        ### content front templates
        field_templates:
            - {template: '@IbexaSeoToolkit/content/view.html.twig', priority: 0}
