# config/routes.yaml
seo_api.analysis:
    path: /api/seo/analysis
    controller: Codein\eZPlatformSeoToolkit\Controller\AnalyzeContentController

seo_api.content_configuration.get:
    path: /api/seo/content-configuration/get