# config/routes.yaml
codein_ibexa_seo_toolkit.robots:
    path: /robots.txt
    controller: Codein\IbexaSeoToolkit\Controller\GetRobotsController

codein_ibexa_seo_toolkit.sitemap:
    path: /sitemap.xml
    controller: Codein\IbexaSeoToolkit\Controller\SitemapController::index
    methods: [GET]

codein_ibexa_seo_toolkit.sitemap_page_result:
    path: /sitemap-{page}.xml
    controller: Codein\IbexaSeoToolkit\Controller\SitemapController::page
    requirements:
        page: '\d+'
    methods: [GET]

codein_ibexa_seo_toolkit.sitemap_page_content_type:
    path: /sitemap-{contentTypeIdentifier}.xml
    controller: Codein\IbexaSeoToolkit\Controller\SitemapController::contentTypePage
    requirements:
        contentTypeIdentifier: '[a-zA-Z0-9][a-zA-Z0-9_]*'
    methods: [GET]

codein_ibexa_seo_toolkit.sitemap_xsl:
    path: /main-sitemap.xsl
    controller: Codein\IbexaSeoToolkit\Controller\SitemapController::xsltStylesheet
    methods: [GET]

