services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    _instanceof:
        Codein\eZPlatformSeoToolkit\Analysis\ParentAnalyzerInterface:
            tags: [ 'codein_ez_platform_seo_toolkit.seo_analyzer.parent_interface' ]
        Codein\eZPlatformSeoToolkit\Analysis\AnalyzerInterface:
            tags: [ 'codein_ez_platform_seo_toolkit.seo_analyzer' ]

    Codein\eZPlatformSeoToolkit\Analysis\:
        resource: '../../Analysis/*'

    Codein\eZPlatformSeoToolkit\Analysis\ParentAnalyzerService: ~

    Codein\eZPlatformSeoToolkit\Controller\:
        resource: '../../Controller/*'

    Codein\eZPlatformSeoToolkit\Routing\ApiLoader:
        tags: ['routing.loader']
    Codein\eZPlatformSeoToolkit\Twig\CodeinEzSeoExtension:
        arguments:
            $siteAccessesByLanguage : '%ezpublish.siteaccesses_by_language%'

    Codein\eZPlatformSeoToolkit\Form\MetasFieldType: ~

    Codein\eZPlatformSeoToolkit\Service\AnalyzeContentService: ~

    Codein\eZPlatformSeoToolkit\Service\SitemapContentService: 
        calls:
            - [setVariationHandler, ["@ezpublish.image_alias.imagine.alias_generator", "@ezpublish.fieldType.ezimage"]]

    Codein\eZPlatformSeoToolkit\EventListener\SitemapResponseListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }