services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    _instanceof:
        Codein\eZPlatformSeoToolkit\Analyzer\RichTextParentAnalyzerInterface:
            tags: [ 'codein_ez_platform_seo_toolkit.seo_analyzer.richtextparent' ]
        Codein\eZPlatformSeoToolkit\Analyzer\ContentPreviewParentAnalyzerInterface:
            tags: [ 'codein_ez_platform_seo_toolkit.seo_analyzer.contentpreviewparent' ]
        Codein\eZPlatformSeoToolkit\Analyzer\RichText\RichTextAnalyzerInterface:
            tags: [ 'codein_ez_platform_seo_toolkit.seo_analyzer.rich_text' ]
        Codein\eZPlatformSeoToolkit\Analyzer\Preview\ContentPreviewAnalyzerInterface:
            tags: [ 'codein_ez_platform_seo_toolkit.seo_analyzer.content_preview' ]

    Codein\eZPlatformSeoToolkit\Analyzer\:
        resource: '../../Analyzer/*'

    Codein\eZPlatformSeoToolkit\Analyzer\ContentPreviewParentAnalyzerService:
        arguments:
            $defaultSiteaccess: '%ezpublish.siteaccess.default%'
            $previewControllerService: '@ezpublish.controller.content.preview.core'

    Codein\eZPlatformSeoToolkit\Analyzer\RichText\WordCountAnalyzer:
        arguments:
            $xhtml5Converter: '@ezrichtext.converter.output.xhtml5'

    Codein\eZPlatformSeoToolkit\Controller\AnalyzeContentController: ~
    Codein\eZPlatformSeoToolkit\Controller\ContentConfigurationController: ~

    Codein\eZPlatformSeoToolkit\Routing\ApiLoader:
        tags: ['routing.loader']
    Codein\eZPlatformSeoToolkit\Twig\CodeineZSeoExtension: ~

    Codein\eZPlatformSeoToolkit\Form\MetasFieldType: ~
