services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    _instanceof:
        Codein\IbexaSeoToolkit\Analysis\ParentAnalyzerInterface:
            tags: [ 'codein_ibexa_seo_toolkit.seo_analyzer.parent_interface' ]
        Codein\IbexaSeoToolkit\Analysis\AnalyzerInterface:
            tags: [ 'codein_ibexa_seo_toolkit.seo_analyzer' ]

    Codein\IbexaSeoToolkit\Analysis\:
        resource: '../../Analysis/*'

    Codein\IbexaSeoToolkit\Analysis\ParentAnalyzerService: ~

    Codein\IbexaSeoToolkit\Controller\:
        resource: '../../Controller/*'

    Codein\IbexaSeoToolkit\Routing\ApiLoader:
        tags: ['routing.loader']
    Codein\IbexaSeoToolkit\Twig\CodeinIbexaSeoExtension:
        arguments:
            $siteAccessesByLanguage : '%ezpublish.siteaccesses_by_language%'

    Codein\IbexaSeoToolkit\Form\MetasFieldType: ~

    Codein\IbexaSeoToolkit\Service\AnalyzeContentService: ~

    Codein\IbexaSeoToolkit\Service\SitemapContentService: 
        calls:
            - [setVariationHandler, ["@ezpublish.image_alias.imagine.alias_generator", "@ezpublish.fieldType.ezimage"]]

    Codein\IbexaSeoToolkit\EventListener\SitemapResponseListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }