services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    _instanceof:
        Codein\eZPlatformSeoToolkit\Analyzer\ParentAnalyzerInterface:
            tags: [ 'codein_ez_platform_seo_toolkit.seo_analyzer.parent' ]
        Codein\eZPlatformSeoToolkit\Analyzer\RichText\RichTextAnalyzerInterface:
            tags: [ 'codein_ez_platform_seo_toolkit.seo_analyzer.rich_text' ]
        Codein\eZPlatformSeoToolkit\Analyzer\Preview\ContentPreviewAnalyzerInterface:
            tags: [ 'codein_ez_platform_seo_toolkit.seo_analyzer.content_preview' ]

    Codein\eZPlatformSeoToolkit\Analyzer\:
        resource: '../../Analyzer/*'
    Codein\eZPlatformSeoToolkit\Controller\:
        resource: '../../Controller/*'

    Codein\eZPlatformSeoToolkit\Analyzer\RichText\WordCountAnalyzer:
        arguments:
            $xhtml5Converter: '@ezrichtext.converter.output.xhtml5'


    Codein\eZPlatformSeoToolkit\Routing\ApiLoader:
        tags: ['routing.loader']
    Codein\eZPlatformSeoToolkit\Twig\CodeineZSeoExtension: ~

    Codein\eZPlatformSeoToolkit\Form\MetasFieldType: ~

    Codein\eZPlatformSeoToolkit\Service\SitemapContentService: 
        calls:
            - [setVariationHandler, ["@ezpublish.image_alias.imagine.alias_generator", "@ezpublish.fieldType.ezimage"]]

    Codein\eZPlatformSeoToolkit\EventListener\SitemapResponseListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }